config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    resources :products, param: :slug_or_id, only: [:show] do
      member do
        get :add_favorite
        delete :remove_favorite
      end
    end
    resources :categories,                   only: [:show]
    resources :users
    resources :orders do
      member do
        get :step1, :step2, :step3, :complete
      end
    end
    get    '/login',                to: 'sessions#new'
    post   '/login',                to: 'sessions#create'
    delete '/logout',               to: 'sessions#destroy'
    get :/,                         to: 'home#index'
    get :index,                     to: 'home#index'
    get :unfinished,                to: 'home#unfinished'
    post :unfinished,               to: 'home#unfinished'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    post '/orders/:id/step1',       to: 'orders#data_set'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/potepan.rb
module Potepan
  def self.table_name_prefix
    'potepan_'
  end
end

app/models/potepan/favorite.rb
class Potepan::Favorite < ApplicationRecord
  validates :user_id, presence: true, uniqueness: { scope: :product_id }
  validates :product_id, presence: true
  belongs_to :product, class_name: 'Spree::Product'
  belongs_to :user
end

app/models/potepan/order.rb
class Potepan::Order < ApplicationRecord
  belongs_to :user
  belongs_to :checkout
  has_many :ordered_products
end

app/models/potepan/ordered_product.rb
class Potepan::OrderedProduct < ApplicationRecord
  belongs_to :order
  validates :order_id, uniqueness: { scope: :product_id }
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  helper_method :option_value, :products_count_filtered_by_color, :products_count_filtered_by_size
  before_action :set_view_type, only: [:show]

  def show
    @taxon = Spree::Taxon.find(params[:id])
    @taxonomies = Spree::Taxonomy.all.includes(:root)
    @options = Spree::OptionType.all.includes(:option_values)
    @numbers = [0, 1, 2, 3]
    @sort_list = ["新着順", "古い順", "値段が安い順", "値段が高い順"]
    @color = option_value(params[:color]).name if params[:color].present?
    @size =  option_value(params[:size]).name if params[:size].present?
    @price_to_amount = [(params[:min].to_i / 110), (params[:max].to_i / 110)]
    @filtered_key = {}

    if filtered_by_size? && sorted?
      @filtered_key[:サイズ] = "#{option_value(params[:size]).name}"
      case params[:sort]
      when '0'
        @products = Spree::Product.filter_by_taxon(@taxon).
          filter_by_size(option_value(params[:size]).name).
          including_images_prices.order("available_on DESC")
        @filtered_key[:並び替え] = "新着順"
      when '1'
        @products = Spree::Product.filter_by_taxon(@taxon).
          filter_by_size(option_value(params[:size]).name).
          including_images_prices.order("available_on ASC")
        @sort_list = @sort_list.values_at(1, 0, 2, 3)
        @numbers = @numbers.values_at(1, 0, 2, 3)
        @filtered_key[:並び替え] = "古い順"
      when '2'
        @products = Spree::Product.filter_by_taxon(@taxon).
          filter_by_size(option_value(params[:size]).name).
          including_images_prices.order("amount ASC")
        @sort_list = @sort_list.values_at(2, 0, 1, 3)
        @numbers = @numbers.values_at(2, 0, 1, 3)
        @filtered_key[:並び替え] = "値段が安い順"
      when '3'
        @products = Spree::Product.filter_by_taxon(@taxon).
          filter_by_size(option_value(params[:size]).name).
          including_images_prices.order("amount DESC")
        @sort_list = @sort_list.values_at(3, 0, 1, 2)
        @numbers = @numbers.values_at(3, 0, 1, 2)
        @filtered_key[:並び替え] = "値段が高い順"
      end

    elsif filtered_by_size?
      @products = Spree::Product.filter_by_taxon(@taxon).
        filter_by_size(option_value(params[:size]).name).
        including_images_prices.order("available_on DESC")
      @filtered_key[:サイズ] = "#{option_value(params[:size]).name}"

    elsif filtered_by_color? && sorted?
      @filtered_key[:カラー] = "#{option_value(params[:color]).name}"
      case params[:sort]
      when '0'
        @products = Spree::Product.filter_by_taxon(@taxon).
          filter_by_color(option_value(params[:color]).name).
          including_images_prices.order("available_on DESC")
        @filtered_key[:並び替え] = "新着順"
      when '1'
        @products = Spree::Product.filter_by_taxon(@taxon).
          filter_by_color(option_value(params[:color]).name).
          including_images_prices.order("available_on ASC")
        @sort_list = @sort_list.values_at(1, 0, 2, 3)
        @numbers = @numbers.values_at(1, 0, 2, 3)
        @filtered_key[:並び替え] = "古い順"
      when '2'
        @products = Spree::Product.filter_by_taxon(@taxon).
          filter_by_color(option_value(params[:color]).name).
          including_images_prices.order("amount ASC")
        @sort_list = @sort_list.values_at(2, 0, 1, 3)
        @numbers = @numbers.values_at(2, 0, 1, 3)
        @filtered_key[:並び替え] = "値段が安い順"
      when '3'
        @products = Spree::Product.filter_by_taxon(@taxon).
          filter_by_color(option_value(params[:color]).name).
          including_images_prices.order("amount DESC")
        @sort_list = @sort_list.values_at(3, 0, 1, 2)
        @numbers = @numbers.values_at(3, 0, 1, 2)
        @filtered_key[:並び替え] = "値段が高い順"
      end

    elsif filtered_by_color?
      @products = Spree::Product.filter_by_taxon(@taxon).
        filter_by_color(option_value(params[:color]).name).
        including_images_prices.order("available_on DESC")
      @filtered_key[:カラー] = "#{option_value(params[:color]).name}"

    elsif filtered_by_price? && sorted?
      @filtered_key[:値段] = "#{params[:min]}円 〜 #{params[:max]}円"
      case params[:sort]
      when '0'
        @products = Spree::Product.filter_by_taxon(@taxon).
          where("amount > ? and amount < ?", @price_to_amount[0], @price_to_amount[1]).
          including_images_prices.order("available_on DESC")
        @filtered_key[:並び替え] = "新着順"
      when '1'
        @products = Spree::Product.filter_by_taxon(@taxon).
          where("amount > ? and amount < ?", @price_to_amount[0], @price_to_amount[1]).
          including_images_prices.order("available_on ASC")
        @sort_list = @sort_list.values_at(1, 0, 2, 3)
        @numbers = @numbers.values_at(1, 0, 2, 3)
        @filtered_key[:並び替え] = "古い順"
      when '2'
        @products = Spree::Product.filter_by_taxon(@taxon).
          where("amount > ? and amount < ?", @price_to_amount[0], @price_to_amount[1]).
          including_images_prices.order("amount ASC")
        @sort_list = @sort_list.values_at(2, 0, 1, 3)
        @numbers = @numbers.values_at(2, 0, 1, 3)
        @filtered_key[:並び替え] = "値段が安い順"
      when '3'
        @products = Spree::Product.filter_by_taxon(@taxon).
          where("amount > ? and amount < ?", @price_to_amount[0], @price_to_amount[1]).
          including_images_prices.order("amount DESC")
        @sort_list = @sort_list.values_at(3, 0, 1, 2)
        @numbers = @numbers.values_at(3, 0, 1, 2)
        @filtered_key[:並び替え] = "値段が高い順"
      end

    elsif filtered_by_price?
      @products = Spree::Product.filter_by_taxon(@taxon).
        where("amount > ? and amount < ?", @price_to_amount[0], @price_to_amount[1]).
        including_images_prices.order("available_on DESC")
      @filtered_key[:値段] = "#{params[:min]}円 〜 #{params[:max]}円"

    elsif sorted?
      case params[:sort]
      when '0'
        @products = Spree::Product.filter_by_taxon(@taxon).
          including_images_prices.order("available_on DESC")
        @filtered_key[:並び替え] = "新着順"
      when '1'
        @products = Spree::Product.filter_by_taxon(@taxon).
          including_images_prices.order("available_on ASC")
        @sort_list = @sort_list.values_at(1, 0, 2, 3)
        @numbers = @numbers.values_at(1, 0, 2, 3)
        @filtered_key[:並び替え] = "古い順"
      when '2'
        @products = Spree::Product.filter_by_taxon(@taxon).
          including_images_prices.order("amount ASC")
        @sort_list = @sort_list.values_at(2, 0, 1, 3)
        @numbers = @numbers.values_at(2, 0, 1, 3)
        @filtered_key[:並び替え] = "値段が安い順"
      when '3'
        @products = Spree::Product.filter_by_taxon(@taxon).
          including_images_prices.order("amount DESC")
        @sort_list = @sort_list.values_at(3, 0, 1, 2)
        @numbers = @numbers.values_at(3, 0, 1, 2)
        @filtered_key[:並び替え] = "値段が高い順"
      end

    else
      @products = Spree::Product.filter_by_taxon(@taxon).
        including_images_prices.order("available_on DESC")
    end
  end

  private

  def option_value(value)
    Spree::OptionValue.find(value)
  end

  def filtered_by_color?
    params[:color].present?
  end

  def filtered_by_size?
    params[:size].present?
  end

  def filtered_by_price?
    params[:min].present? && params[:max].present?
  end

  def sorted?
    params[:sort].present?
  end

  def products_count_filtered_by_color(value)
    Spree::Product.filter_by_taxon(@taxon).filter_by_color(value).ids.uniq.count
  end

  def products_count_filtered_by_size(value)
    Spree::Product.filter_by_taxon(@taxon).filter_by_size(value).ids.uniq.count
  end

  def set_view_type
    if params[:format] == 'list'
      session[:format] = 'list'
    elsif params[:format] == 'grid'
      session[:format] = 'grid'
    end
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  COUNT_OF_LATED_PRODUCTS = 8
  def index
    @lated_products = Spree::Product.including_images_prices.
      order(available_on: :desc).limit(COUNT_OF_LATED_PRODUCTS)

    @shirts = Spree::Taxon.find_by(permalink: "categories/clothing/t-shirt") ||
              Spree::Taxon.find_by(name: "Tシャツ")
    @bags = Spree::Taxon.find_by(permalink: "categories/bags") || Spree::Taxon.find_by(name: "バッグ")
    @mugs = Spree::Taxon.find_by(permalink: "categories/mugs") || Spree::Taxon.find_by(name: "マグ")
  end

  def unfinished
  end
end

app/controllers/potepan/orders_controller.rb
class Potepan::OrdersController < ApplicationController
  helper_method :products_count
  before_action :check_logged_in, only: [:show, :update, :destroy, :step1, :step2, :step3, :complete, :data_set]
  before_action :check_logged_in_for_ajax, only: [:create]
  def show
    @order = Potepan::Order.find(params[:id])
    product_ids = Potepan::OrderedProduct.where(order_id: params[:id]).pluck(:product_id)
    @products = Spree::Product.where(id: product_ids)
    @item_total = 0
    @products.each do |product|
      if products_count(product.id) == 1
        @item_total += (product.price * 110).to_i
      else
        @item_total += products_count(product.id).to_i * (product.price * 110).to_i
      end
    end
  end

  def create
    order = Potepan::Order.find_by(user_id: current_user.id, state: 1)
    product = Spree::Product.find(params[:id])
    orderedproduct = Potepan::OrderedProduct.find_by(order_id: order.id, product_id: params[:id])

    if order.present? && orderedproduct.present?
      orderedproduct.count += 1
    elsif order.present?
      orderedproduct = Potepan::OrderedProduct.new
      orderedproduct.order_id = order.id
      orderedproduct.product_id = product.id
      orderedproduct.count = 1
      orderedproduct.save
    else
      order = Potepan::Order.new
      order.user_id = current_user.id
      order.state = 1
      order.save
      orderedproduct = Potepan::OrderedProduct.new
      orderedproduct.order_id = order.id
      orderedproduct.product_id = product.id
      orderedproduct.count = 1
    end
    orderedproduct.save
  end

  def update
    product_ids = Potepan::OrderedProduct.where(order_id: params[:id]).pluck(:product_id)
    product_ids.each do |product_id|
      product = Potepan::OrderedProduct.find_by(order_id: params[:id], product_id: product_id)
      product.count = params["#{product_id}"]
      product.save
    end
    flash[:success] = "カートの中身を最新の状態に更新しました"
    redirect_to potepan_order_path(params[:id])
  end

  def destroy
    order_id = params[:id]
    product_id = params[:product_id]
    Potepan::OrderedProduct.find_by(order_id: order_id, product_id: product_id).delete
    flash[:success] = "カートから商品を削除しました"
    redirect_to potepan_order_path(order_id)
  end

  def step1
    order = Potepan::OrderedProduct.find_by(order_id: params[:id])
    if order.nil?
      flash[:danger] = "カートに商品が入っていません"
      redirect_to potepan_order_path(params[:id])
    end
    @checkout = Potepan::Checkout.new
  end

  def data_set
    @checkout = Potepan::Checkout.find_by(order_id: params[:id])
    @checkout = Potepan::Checkout.new if @checkout.nil?
    user = Potepan::Order.find(params[:id]).user
    if params[:check_name].nil?
      @checkout.name = params[:potepan_checkout][:name]
    else
      @checkout.name = user.name
    end
    if params[:check_email].nil? && @checkout.email.nil?
      @checkout.email = params[:potepan_checkout][:email]
    else
      @checkout.email = user.email
    end
    if params[:check_streetaddress].nil? && @checkout.streetaddress.nil?
      @checkout.streetaddress = params[:potepan_checkout][:streetaddress]
    else
      @checkout.streetaddress = user.streetaddress
    end
    if params[:check_phone].nil? && @checkout.phone.nil?
      @checkout.phone = params[:potepan_checkout][:phone]
    else
      @checkout.phone = user.phone
    end
    if params[:check_postal].nil? && @checkout.postal.nil?
      @checkout.postal = params[:potepan_checkout][:postal]
    else
      @checkout.postal = user.postal
    end
    @checkout.order_id = params[:id]
    @checkout.state = 1
    if @checkout.save
      redirect_to step2_potepan_order_path
    else
      flash.now[:danger] = 'お届け先情報を登録に失敗しました'
      render 'step1'
    end
  end

  def step2
  end

  def step3
    @order = Potepan::Order.find(params[:id])
    @user = @order.user
    @checkout = Potepan::Checkout.find_by(order_id: @order.id)
    product_ids = Potepan::OrderedProduct.where(order_id: params[:id]).pluck(:product_id)
    @products = Spree::Product.where(id: product_ids)
    @item_total = 0
    @products.each do |product|
      if products_count(product.id) == 1
        @item_total += (product.price * 110).to_i
      else
        @item_total += products_count(product.id).to_i * (product.price * 110).to_i
      end
    end
  end

  def complete
    @order = Potepan::Order.find(params[:id])
    @checkout = Potepan::Checkout.find_by(order_id: @order.id)
    @order.state = 2
    @order.save
    @checkout.state = 2
    @checkout.save
  end

  private

  def products_count(id)
    Potepan::OrderedProduct.find_by(order_id: params[:id], product_id: id).count
  end

  def check_logged_in
    unless logged_in?
      flash[:danger] = "ログインしてください"
      redirect_to potepan_path
    end
  end

  def check_logged_in_for_ajax
    unless logged_in?
      flash[:danger] = "ログインしてください"
      render :js => "window.location = '/potepan'"
    end
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  before_action :check_logged_in, only: [:add_favorite, :remove_favorite]
  COUNT_OF_RELATED_PRODUCTS = 4
  def show
    @product = Spree::Product.friendly.find(params[:slug_or_id])
    @product_properties = @product.product_properties.includes(:property)
    @related_products = Spree::Product.related_products(@product).
      including_images_prices.limit(COUNT_OF_RELATED_PRODUCTS)
  end

  def add_favorite
    product = Spree::Product.find(params[:slug_or_id])
    user = Potepan::User.find(current_user.id)
    favorite = Potepan::Favorite.find_by(user_id: user.id, product_id: product.id)
    if favorite.present?
      render 'add_favorite_false_01'
    else
      favorite = Potepan::Favorite.new
      favorite.user_id = user.id
      favorite.product_id = product.id
      if favorite.save
        render 'add_favorite'
      else
        render 'add_favorite_false_02'
      end
    end
  end

  def remove_favorite
    Potepan::Favorite.find_by(user_id: current_user.id, product_id: params[:slug_or_id]).delete
    flash[:danger] = "お気に入りから削除しました"
    redirect_back(fallback_location: potepan_path)
  end

  private
  def check_logged_in
    unless logged_in?
      flash[:danger] = 'ログインしてください'
      render :js => "window.location = '/potepan'"
    end
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/controllers/potepan/sessions_controller.rb
class Potepan::SessionsController < ApplicationController
  def new
  end

  def create
    user = Potepan::User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "ログインしました"
      log_in(user)
      redirect_to potepan_path
    else
      flash.now[:danger] = "メールアドレスかパスワードが間違っています"
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:success] = "ログアウトしました"
    redirect_to potepan_path
  end
end

app/views/potepan/categories/_filter_by_color.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色で絞り込み</div>
  <div class="panel-body">
    <ul class="list-unstyled">
      <% @options.find_by(presentation: 'Color').option_values.each do |color_option| %>
      <li>
        <%= link_to potepan_category_path(params[:id], color: color_option.id) do %>
          <%= color_option.presentation %><span>(<%= products_count_filtered_by_color(color_option.name) %>)</span>
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/categories/_filter_by_price.html.erb
<div class="panel panel-default priceRange">
  <div class="panel-heading">値段で絞り込み</div>
  <div class="panel-body clearfix">
    <div class="price-slider-inner">
      <span class="amount-wrapper">
        <input type="text" id="price-amount-1" readonly>
        <strong>-</strong>
        <input type="text" id="price-amount-2" readonly>
      </span>
      <div id="price-range"></div>
    </div>
    <input class="btn btn-default" id='price_button' type="submit" value="実行">
  </div>
</div>

app/views/potepan/categories/_filter_by_size.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">サイズで絞り込み</div>
  <div class="panel-body">
    <ul class="list-unstyled">
      <% @options.find_by(presentation: 'Size').option_values.each do |size_option| %>
      <li>
        <%= link_to potepan_category_path(params[:id], size: size_option.id) do %>
          <%= size_option.presentation %><span>(<%= products_count_filtered_by_size(size_option.name) %>)</span>
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/categories/_filter_by_taxon.html.erb
<div class="panel panel-default">
  <div class="panel-heading">カテゴリかブランドで絞り込み</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <% taxonomies.each do |taxonomy| %>
        <li>
          <a href="javascript:;" data-toggle="collapse" data-target="#<%= taxonomy.id %>">
            <%= taxonomy.name %><i class="fa fa-plus"></i>
          </a>
          <ul id="<%= taxonomy.id %>" class="collapse collapseItem">
            <li>
              <%= link_to potepan_category_path(taxonomy.root.id) do %>
                <i class="fa fa-caret-right" aria-hidden="true"></i>
                全て <span>(<%= Spree::Product.in_taxon(taxonomy.root).count %>)</span>
              <% end %>
            </li>
            <% taxonomy.root.leaves.each do |taxon| %>
            <li>
              <%= link_to potepan_category_path(taxon.id) do %>
                <i class="fa fa-caret-right" aria-hidden="true"></i>
                <%= taxon.name %> <span>(<%= taxon.products.count %>)</span>
              <% end %>
            </li>
            <% end %>
          </ul>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/_product_for_grid.html.erb
<div class="col-sm-4 col-xs-12">
  <div class="productBox">
    <%= render partial: 'shared/product', locals: { product: product, image_size: :small } %>
  </div>
</div>

app/views/potepan/categories/_product_for_list.html.erb
<div class="col-xs-12">
  <div class="media">
    <div class="media-left">
      <%= image_tag product.display_image.attachment.url(:product), :class => "media-object", :alt => product.name %>
      <span class="maskingImage"><a data-toggle="modal" href=".quick-view" class="btn viewBtn">Quick View</a></span>
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= link_to product.name, potepan_product_path(product) %></h4>
      <p><%= product.description %></p>
      <h3><%= (product.price * 110).to_i %>円</h3>
      <div class="btn-group" role="group">
        <%= link_to potepan_unfinished_path, class: 'btn btn-default' do %>
          <button type="button" class="btn btn-default"><i class="fa fa-heart" aria-hidden="true"></i></button>
        <% end %>
        <%= link_to potepan_orders_path(id: product.id ), method: :post do %>
          <button type="button" class="btn btn-default"><i class="fa fa-shopping-cart" aria-hidden="true"></i></button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/potepan/categories/_products_index.html.erb
<div class="col-md-9 col-sm-8 col-xs-12">
  <div class="row">
    <h3>現在の検索条件</h3>
    <% @filtered_key.each do |key, value| %>
       <li><%= key %>：<%= value %></li>
    <% end %>
  </div>
  <div class="row filterArea">
    <div class="col-xs-4">
      <select name="guiest_id1" id="guiest_id1" class="select-drop">
        <% @numbers.zip(@sort_list) do |number, sort| %>
          <option value="<%= number %>" class='sort_tag' id="<%= number %>"><%= sort %></option>
        <% end %>
      </select>
    </div>
    <div class="col-xs-4">
      <div class="btn-group pull-right" role="group">
        <%= link_to potepan_category_path(params[:id]) do %>
          <button type="button" class="btn btn-default">
            <span>リセット</span>
          </button>
        <% end %>
      </div>
    </div>
    <div class="col-xs-4">
      <div class="btn-group pull-right" role="group">
        <%= link_to potepan_category_path(params[:id], format: "grid",
                                                       type: params[:type],
                                                       color: params[:color]
                                          ) do %>
          <button type="button" class="btn btn-default <%= "active" if grid_type? %>">
            <i class="fa fa-th-list" aria-hidden="true"></i><span>グリッド</span>
          </button>
        <% end %>
        <%= link_to potepan_category_path(params[:id], format: "list",
                                                       type: params[:type],
                                                       color: params[:color]
                                          ) do %>
          <button type="button" class="btn btn-default <%= "active" if list_type? %>">
            <i class="fa fa-th-list" aria-hidden="true"></i><span>リスト</span>
          </button>
        <% end %>
      </div>
    </div>
  </div>

  <!-- JS用のhiddenデータ -->
  <input type='hidden' value="<%= params[:id] %>" class='id_data'>
  <input type='hidden' value="<%= params[:color] %>" class='color_data'>
  <input type='hidden' value="<%= params[:size] %>" class='size_data'>
  <input type='hidden' value="<%= params[:min] %>" class='min_data'>
  <input type='hidden' value="<%= params[:max] %>" class='max_data'>

  <% if list_type? %>
    <div class="row productListSingle">
      <%= render partial: 'product_for_list', collection: products, as: :product %>
    </div>
  <% elsif grid_type? %>
    <div class="row">
      <%= render partial: 'product_for_grid', collection: products, as: :product %>
    </div>
  <% end %>
</div>

app/views/potepan/categories/show.html.erb
<!-- SITE TITTLE -->
<% provide(:title, @taxon.name) %>
<%= render partial: 'shared/page_header', locals: { title: @taxon.name, active: @taxon.name } %>
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <%= render partial: 'filter_by_taxon', locals: { taxonomies: @taxonomies } %>
        <%= render 'filter_by_price' %>
        <%= render 'filter_by_color' %>
        <%= render 'filter_by_size' %>
      </div>
      <%= render partial: 'products_index', locals: { products: @products } %>
    </div>
  </div>
</section>
<%= render 'shared/bottom_light' %>