config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    resources :products, param: :slug_or_id, only: [:show] do
      member do
        get :add_favorite
        delete :remove_favorite
      end
    end
    resources :categories,                   only: [:show]
    resources :users
    resources :orders do
      member do
        get :step1, :step2, :step3, :complete
      end
    end
    get    '/login',                to: 'sessions#new'
    post   '/login',                to: 'sessions#create'
    delete '/logout',               to: 'sessions#destroy'
    get :/,                         to: 'home#index'
    get :index,                     to: 'home#index'
    get :unfinished,                to: 'home#unfinished'
    post :unfinished,               to: 'home#unfinished'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    post '/orders/:id/step1',       to: 'orders#data_set'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/potepan.rb
module Potepan
  def self.table_name_prefix
    'potepan_'
  end
end

app/models/potepan/favorite.rb
class Potepan::Favorite < ApplicationRecord
  validates :user_id, presence: true, uniqueness: { scope: :product_id }
  validates :product_id, presence: true
  belongs_to :product, class_name: 'Spree::Product'
  belongs_to :user
end

app/models/potepan/order.rb
class Potepan::Order < ApplicationRecord
  belongs_to :user
  belongs_to :checkout
  has_many :ordered_products
end

app/models/potepan/ordered_product.rb
class Potepan::OrderedProduct < ApplicationRecord
  belongs_to :order
  validates :order_id, uniqueness: { scope: :product_id }
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  helper_method :option_value, :products_count_filtered_by_color, :products_count_filtered_by_size
  before_action :set_view_type, only: [:show]

  def show
    @taxon = Spree::Taxon.find(params[:id])
    @taxonomies = Spree::Taxonomy.all.includes(:root)
    @options = Spree::OptionType.all.includes(:option_values)
    @numbers = [0, 1, 2, 3]
    @sort_list = ["新着順", "古い順", "値段が安い順", "値段が高い順"]
    @color = option_value(params[:color]).name if params[:color].present?
    @size =  option_value(params[:size]).name if params[:size].present?
    @price_to_amount = [(params[:min].to_i / 110), (params[:max].to_i / 110)]
    @filtered_key = {}

    if filtered_by_size? && sorted?
      @filtered_key[:サイズ] = "#{option_value(params[:size]).name}"
      case params[:sort]
      when '0'
        @products = Spree::Product.filter_by_taxon(@taxon).
          filter_by_size(option_value(params[:size]).name).
          including_images_prices.order("available_on DESC")
        @filtered_key[:並び替え] = "新着順"
      when '1'
        @products = Spree::Product.filter_by_taxon(@taxon).
          filter_by_size(option_value(params[:size]).name).
          including_images_prices.order("available_on ASC")
        @sort_list = @sort_list.values_at(1, 0, 2, 3)
        @numbers = @numbers.values_at(1, 0, 2, 3)
        @filtered_key[:並び替え] = "古い順"
      when '2'
        @products = Spree::Product.filter_by_taxon(@taxon).
          filter_by_size(option_value(params[:size]).name).
          including_images_prices.order("amount ASC")
        @sort_list = @sort_list.values_at(2, 0, 1, 3)
        @numbers = @numbers.values_at(2, 0, 1, 3)
        @filtered_key[:並び替え] = "値段が安い順"
      when '3'
        @products = Spree::Product.filter_by_taxon(@taxon).
          filter_by_size(option_value(params[:size]).name).
          including_images_prices.order("amount DESC")
        @sort_list = @sort_list.values_at(3, 0, 1, 2)
        @numbers = @numbers.values_at(3, 0, 1, 2)
        @filtered_key[:並び替え] = "値段が高い順"
      end

    elsif filtered_by_size?
      @products = Spree::Product.filter_by_taxon(@taxon).
        filter_by_size(option_value(params[:size]).name).
        including_images_prices.order("available_on DESC")
      @filtered_key[:サイズ] = "#{option_value(params[:size]).name}"

    elsif filtered_by_color? && sorted?
      @filtered_key[:カラー] = "#{option_value(params[:color]).name}"
      case params[:sort]
      when '0'
        @products = Spree::Product.filter_by_taxon(@taxon).
          filter_by_color(option_value(params[:color]).name).
          including_images_prices.order("available_on DESC")
        @filtered_key[:並び替え] = "新着順"
      when '1'
        @products = Spree::Product.filter_by_taxon(@taxon).
          filter_by_color(option_value(params[:color]).name).
          including_images_prices.order("available_on ASC")
        @sort_list = @sort_list.values_at(1, 0, 2, 3)
        @numbers = @numbers.values_at(1, 0, 2, 3)
        @filtered_key[:並び替え] = "古い順"
      when '2'
        @products = Spree::Product.filter_by_taxon(@taxon).
          filter_by_color(option_value(params[:color]).name).
          including_images_prices.order("amount ASC")
        @sort_list = @sort_list.values_at(2, 0, 1, 3)
        @numbers = @numbers.values_at(2, 0, 1, 3)
        @filtered_key[:並び替え] = "値段が安い順"
      when '3'
        @products = Spree::Product.filter_by_taxon(@taxon).
          filter_by_color(option_value(params[:color]).name).
          including_images_prices.order("amount DESC")
        @sort_list = @sort_list.values_at(3, 0, 1, 2)
        @numbers = @numbers.values_at(3, 0, 1, 2)
        @filtered_key[:並び替え] = "値段が高い順"
      end

    elsif filtered_by_color?
      @products = Spree::Product.filter_by_taxon(@taxon).
        filter_by_color(option_value(params[:color]).name).
        including_images_prices.order("available_on DESC")
      @filtered_key[:カラー] = "#{option_value(params[:color]).name}"

    elsif filtered_by_price? && sorted?
      @filtered_key[:値段] = "#{params[:min]}円 〜 #{params[:max]}円"
      case params[:sort]
      when '0'
        @products = Spree::Product.filter_by_taxon(@taxon).
          where("amount > ? and amount < ?", @price_to_amount[0], @price_to_amount[1]).
          including_images_prices.order("available_on DESC")
        @filtered_key[:並び替え] = "新着順"
      when '1'
        @products = Spree::Product.filter_by_taxon(@taxon).
          where("amount > ? and amount < ?", @price_to_amount[0], @price_to_amount[1]).
          including_images_prices.order("available_on ASC")
        @sort_list = @sort_list.values_at(1, 0, 2, 3)
        @numbers = @numbers.values_at(1, 0, 2, 3)
        @filtered_key[:並び替え] = "古い順"
      when '2'
        @products = Spree::Product.filter_by_taxon(@taxon).
          where("amount > ? and amount < ?", @price_to_amount[0], @price_to_amount[1]).
          including_images_prices.order("amount ASC")
        @sort_list = @sort_list.values_at(2, 0, 1, 3)
        @numbers = @numbers.values_at(2, 0, 1, 3)
        @filtered_key[:並び替え] = "値段が安い順"
      when '3'
        @products = Spree::Product.filter_by_taxon(@taxon).
          where("amount > ? and amount < ?", @price_to_amount[0], @price_to_amount[1]).
          including_images_prices.order("amount DESC")
        @sort_list = @sort_list.values_at(3, 0, 1, 2)
        @numbers = @numbers.values_at(3, 0, 1, 2)
        @filtered_key[:並び替え] = "値段が高い順"
      end

    elsif filtered_by_price?
      @products = Spree::Product.filter_by_taxon(@taxon).
        where("amount > ? and amount < ?", @price_to_amount[0], @price_to_amount[1]).
        including_images_prices.order("available_on DESC")
      @filtered_key[:値段] = "#{params[:min]}円 〜 #{params[:max]}円"

    elsif sorted?
      case params[:sort]
      when '0'
        @products = Spree::Product.filter_by_taxon(@taxon).
          including_images_prices.order("available_on DESC")
        @filtered_key[:並び替え] = "新着順"
      when '1'
        @products = Spree::Product.filter_by_taxon(@taxon).
          including_images_prices.order("available_on ASC")
        @sort_list = @sort_list.values_at(1, 0, 2, 3)
        @numbers = @numbers.values_at(1, 0, 2, 3)
        @filtered_key[:並び替え] = "古い順"
      when '2'
        @products = Spree::Product.filter_by_taxon(@taxon).
          including_images_prices.order("amount ASC")
        @sort_list = @sort_list.values_at(2, 0, 1, 3)
        @numbers = @numbers.values_at(2, 0, 1, 3)
        @filtered_key[:並び替え] = "値段が安い順"
      when '3'
        @products = Spree::Product.filter_by_taxon(@taxon).
          including_images_prices.order("amount DESC")
        @sort_list = @sort_list.values_at(3, 0, 1, 2)
        @numbers = @numbers.values_at(3, 0, 1, 2)
        @filtered_key[:並び替え] = "値段が高い順"
      end

    else
      @products = Spree::Product.filter_by_taxon(@taxon).
        including_images_prices.order("available_on DESC")
    end
  end

  private

  def option_value(value)
    Spree::OptionValue.find(value)
  end

  def filtered_by_color?
    params[:color].present?
  end

  def filtered_by_size?
    params[:size].present?
  end

  def filtered_by_price?
    params[:min].present? && params[:max].present?
  end

  def sorted?
    params[:sort].present?
  end

  def products_count_filtered_by_color(value)
    Spree::Product.filter_by_taxon(@taxon).filter_by_color(value).ids.uniq.count
  end

  def products_count_filtered_by_size(value)
    Spree::Product.filter_by_taxon(@taxon).filter_by_size(value).ids.uniq.count
  end

  def set_view_type
    if params[:format] == 'list'
      session[:format] = 'list'
    elsif params[:format] == 'grid'
      session[:format] = 'grid'
    end
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  COUNT_OF_LATED_PRODUCTS = 8
  def index
    @lated_products = Spree::Product.including_images_prices.
      order(available_on: :desc).limit(COUNT_OF_LATED_PRODUCTS)

    @shirts = Spree::Taxon.find_by(permalink: "categories/clothing/t-shirt") ||
              Spree::Taxon.find_by(name: "Tシャツ")
    @bags = Spree::Taxon.find_by(permalink: "categories/bags") || Spree::Taxon.find_by(name: "バッグ")
    @mugs = Spree::Taxon.find_by(permalink: "categories/mugs") || Spree::Taxon.find_by(name: "マグ")
  end

  def unfinished
  end
end

app/controllers/potepan/orders_controller.rb
class Potepan::OrdersController < ApplicationController
  helper_method :products_count
  before_action :check_logged_in, only: [:show, :update, :destroy, :step1, :step2, :step3, :complete, :data_set]
  before_action :check_logged_in_for_ajax, only: [:create]
  def show
    @order = Potepan::Order.find(params[:id])
    product_ids = Potepan::OrderedProduct.where(order_id: params[:id]).pluck(:product_id)
    @products = Spree::Product.where(id: product_ids)
    @item_total = 0
    @products.each do |product|
      if products_count(product.id) == 1
        @item_total += (product.price * 110).to_i
      else
        @item_total += products_count(product.id).to_i * (product.price * 110).to_i
      end
    end
  end

  def create
    order = Potepan::Order.find_by(user_id: current_user.id, state: 1)
    product = Spree::Product.find(params[:id])
    orderedproduct = Potepan::OrderedProduct.find_by(order_id: order.id, product_id: params[:id])

    if order.present? && orderedproduct.present?
      orderedproduct.count += 1
    elsif order.present?
      orderedproduct = Potepan::OrderedProduct.new
      orderedproduct.order_id = order.id
      orderedproduct.product_id = product.id
      orderedproduct.count = 1
      orderedproduct.save
    else
      order = Potepan::Order.new
      order.user_id = current_user.id
      order.state = 1
      order.save
      orderedproduct = Potepan::OrderedProduct.new
      orderedproduct.order_id = order.id
      orderedproduct.product_id = product.id
      orderedproduct.count = 1
    end
    orderedproduct.save
  end

  def update
    product_ids = Potepan::OrderedProduct.where(order_id: params[:id]).pluck(:product_id)
    product_ids.each do |product_id|
      product = Potepan::OrderedProduct.find_by(order_id: params[:id], product_id: product_id)
      product.count = params["#{product_id}"]
      product.save
    end
    flash[:success] = "カートの中身を最新の状態に更新しました"
    redirect_to potepan_order_path(params[:id])
  end

  def destroy
    order_id = params[:id]
    product_id = params[:product_id]
    Potepan::OrderedProduct.find_by(order_id: order_id, product_id: product_id).delete
    flash[:success] = "カートから商品を削除しました"
    redirect_to potepan_order_path(order_id)
  end

  def step1
    order = Potepan::OrderedProduct.find_by(order_id: params[:id])
    if order.nil?
      flash[:danger] = "カートに商品が入っていません"
      redirect_to potepan_order_path(params[:id])
    end
    @checkout = Potepan::Checkout.new
  end

  def data_set
    @checkout = Potepan::Checkout.find_by(order_id: params[:id])
    @checkout = Potepan::Checkout.new if @checkout.nil?
    user = Potepan::Order.find(params[:id]).user
    if params[:check_name].nil?
      @checkout.name = params[:potepan_checkout][:name]
    else
      @checkout.name = user.name
    end
    if params[:check_email].nil? && @checkout.email.nil?
      @checkout.email = params[:potepan_checkout][:email]
    else
      @checkout.email = user.email
    end
    if params[:check_streetaddress].nil? && @checkout.streetaddress.nil?
      @checkout.streetaddress = params[:potepan_checkout][:streetaddress]
    else
      @checkout.streetaddress = user.streetaddress
    end
    if params[:check_phone].nil? && @checkout.phone.nil?
      @checkout.phone = params[:potepan_checkout][:phone]
    else
      @checkout.phone = user.phone
    end
    if params[:check_postal].nil? && @checkout.postal.nil?
      @checkout.postal = params[:potepan_checkout][:postal]
    else
      @checkout.postal = user.postal
    end
    @checkout.order_id = params[:id]
    @checkout.state = 1
    if @checkout.save
      redirect_to step2_potepan_order_path
    else
      flash.now[:danger] = 'お届け先情報を登録に失敗しました'
      render 'step1'
    end
  end

  def step2
  end

  def step3
    @order = Potepan::Order.find(params[:id])
    @user = @order.user
    @checkout = Potepan::Checkout.find_by(order_id: @order.id)
    product_ids = Potepan::OrderedProduct.where(order_id: params[:id]).pluck(:product_id)
    @products = Spree::Product.where(id: product_ids)
    @item_total = 0
    @products.each do |product|
      if products_count(product.id) == 1
        @item_total += (product.price * 110).to_i
      else
        @item_total += products_count(product.id).to_i * (product.price * 110).to_i
      end
    end
  end

  def complete
    @order = Potepan::Order.find(params[:id])
    @checkout = Potepan::Checkout.find_by(order_id: @order.id)
    @order.state = 2
    @order.save
    @checkout.state = 2
    @checkout.save
  end

  private

  def products_count(id)
    Potepan::OrderedProduct.find_by(order_id: params[:id], product_id: id).count
  end

  def check_logged_in
    unless logged_in?
      flash[:danger] = "ログインしてください"
      redirect_to potepan_path
    end
  end

  def check_logged_in_for_ajax
    unless logged_in?
      flash[:danger] = "ログインしてください"
      render :js => "window.location = '/potepan'"
    end
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  before_action :check_logged_in, only: [:add_favorite, :remove_favorite]
  COUNT_OF_RELATED_PRODUCTS = 4
  def show
    @product = Spree::Product.friendly.find(params[:slug_or_id])
    @product_properties = @product.product_properties.includes(:property)
    @related_products = Spree::Product.related_products(@product).
      including_images_prices.limit(COUNT_OF_RELATED_PRODUCTS)
  end

  def add_favorite
    product = Spree::Product.find(params[:slug_or_id])
    user = Potepan::User.find(current_user.id)
    favorite = Potepan::Favorite.find_by(user_id: user.id, product_id: product.id)
    if favorite.present?
      render 'add_favorite_false_01'
    else
      favorite = Potepan::Favorite.new
      favorite.user_id = user.id
      favorite.product_id = product.id
      if favorite.save
        render 'add_favorite'
      else
        render 'add_favorite_false_02'
      end
    end
  end

  def remove_favorite
    Potepan::Favorite.find_by(user_id: current_user.id, product_id: params[:slug_or_id]).delete
    flash[:danger] = "お気に入りから削除しました"
    redirect_back(fallback_location: potepan_path)
  end

  private
  def check_logged_in
    unless logged_in?
      flash[:danger] = 'ログインしてください'
      render :js => "window.location = '/potepan'"
    end
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/controllers/potepan/sessions_controller.rb
class Potepan::SessionsController < ApplicationController
  def new
  end

  def create
    user = Potepan::User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "ログインしました"
      log_in(user)
      redirect_to potepan_path
    else
      flash.now[:danger] = "メールアドレスかパスワードが間違っています"
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:success] = "ログアウトしました"
    redirect_to potepan_path
  end
end

app/views/potepan/users/edit.html.erb
<% provide(:title, "登録情報編集") %>
<div class="text-center" id='sign_up_box'>
  <h1>編集フォーム</h1>
  <div class="container">
    <%= form_for(@user, url: potepan_user_path, method: :patch) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :名前 %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :メール %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :"携帯電話番号 (ハイフンなし半角数字)" %>
        <%= f.text_field :phone, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :"郵便番号 (ハイフンなし半角数字)" %>
        <%= f.text_field :postal, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :住所 %>
        <%= f.text_field :streetaddress, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :パスワード（変更しない場合は省略可能） %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :パスワードの確認（変更しない場合は省略可能） %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <%= f.submit "編集", class: "btn btn-info btn-block" %>
    <% end %>
    <div class="unsubscribed-section">
      <%= link_to '退会手続きはこちらから', potepan_user_path, method: :delete, data: {confirm: "本当に退会してよろしいですか？"} %>
    </div>
  </div>
</div>

app/views/potepan/users/new.html.erb
<% provide(:title, "会員登録") %>
<div class="text-center" id='sign_up_box'>
  <h1>会員登録フォーム</h1>
  <div class="container">
    <%= form_for(@user, url: potepan_users_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.label :名前 %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :メール %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :パスワード %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :パスワードの確認 %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <%= f.submit "会員登録", class: "btn btn-info btn-block" %>
    <% end %>
  </div>
</div>

app/views/potepan/users/show.html.erb
<% provide(:title, "ダッシュボード") %>

<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2>ユーザーページ</h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to 'Home', potepan_path %>
          </li>
          <li class="active">ユーザーページ</li>
        </ol>
      </div>
    </div>
  </div>
</section>

<section class="mainContent clearfix aboutUsInfo">
  <div class="container">
    <div class="row">
      <div class="page-header">
        <h3 class='user_head'>登録情報</h3>
        <h4 class="pull-right"><%= link_to '編集', edit_potepan_user_path, id: 'user_edit_link' %></h4>
      </div>
      <p class="user_data">名前 : <%= @user.name %></p>
      <p class="user_data">メールアドレス : <%= @user.email %></p>
      <p class="user_data">電話番号 : <%= @user.phone %></p>
      <p class="user_data">郵便番号 : <%= @user.postal %></p>
      <p class="user_data">住所 : <%= @user.streetaddress %></p>
    </div>
  </div>
</section>
<section class="mainContent clearfix aboutUsInfo">
  <div class="container">
    <div class="page-header">
      <h3 class='user_head'>注文履歴</h3>
    </div>
    <div class="row eq-height">
      <% @orders.each do |order| %>
      <div class="col-xs-5 ordered_product_box">
        <span class="box-title">注文番号：<%= order.id %></span>
        <p class="user_data">購入日時：<%= bought_date(order.id) %></p>
        <% @products = bought_products(order.ordered_products.pluck(:product_id)) %>
        <% @products.each do |product| %>
          <p class="user_data product_data">購入商品：<%= link_to product.name, potepan_product_path(product.id), id: 'user_edit_link'  %></p>
          <p class="user_data product_data">商品単価：<%= (product.price * 110).to_i  %> 円</p>
          <p class="user_data product_data">購入数：<%= (bought_products_count(product, order))   %> 個</p>
          <div class="ordered_products_image"><%= image_tag product.images.first.attachment.url(:small) %></div>
        <% end %>
        <p class="user_data">税込金額：<%= (bought_price(@products, order) * 110).to_i  %> 円</p>
      </div>
      <% end %>
    </div>
  </div>
</section>
<section class="mainContent clearfix aboutUsInfo">
  <div class="container">
      <div class="page-header">
        <h3 class='user_head'>お気に入り</h3>
      </div>
      <div class="row eq-height">
      <% @favorite_products.each do |favorite| %>
        <div class="col-xs-5 ordered_product_box">
          <p class="user_data product_data">商品名：<%= link_to favorite.product.name, potepan_product_path(favorite.product.id), id: 'user_edit_link'  %></p>
          <p class="user_data product_data">商品単価：<%= (favorite.product.price * 110).to_i   %> 円</p>
          <p class="user_data product_data"><%= link_to 'カートに追加', potepan_orders_path(id: favorite.product.id ), method: :post, id: 'user_edit_link' %></p>
          <p class="user_data product_data"><%= link_to '削除', remove_favorite_potepan_product_path(favorite.product.id), method: :delete, id: 'user_edit_link' %></p>
          <div class="ordered_products_image"><%= image_tag favorite.product.images.first.attachment.url(:small)  %></div>
        </div>
        <% end %>
      </div>
    </div>
</section>