config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    resources :products, param: :slug_or_id, only: [:show] do
      member do
        get :add_favorite
        delete :remove_favorite
      end
    end
    resources :categories,                   only: [:show]
    resources :users
    resources :orders do
      member do
        get :step1, :step2, :step3, :complete
      end
    end
    get    '/login',                to: 'sessions#new'
    post   '/login',                to: 'sessions#create'
    delete '/logout',               to: 'sessions#destroy'
    get :/,                         to: 'home#index'
    get :index,                     to: 'home#index'
    get :unfinished,                to: 'home#unfinished'
    post :unfinished,               to: 'home#unfinished'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    post '/orders/:id/step1',       to: 'orders#data_set'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_copy_right.html.erb
<!-- COPY RIGHT -->
<div class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016 Copyright Bigbag Store Bootstrap Template by <a target="_blank" href="http://www.iamabdus.com/">Abdus</a>.</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<div class="footer clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <div class="footerLink">
          <ul class="list-unstyled">
            <li class='footer_parts'><%= link_to '運営会社', potepan_about_us_path %></li>
            <li class='footer_parts'><%= link_to 'プライバシーポリシー', potepan_privacy_policy_path %></li>
            <li class='footer_parts'><%= link_to '特定商品取引法', potepan_tokushoho_path %></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="newsletter clearfix">
          <h4>Newsletter</h4>
          <h3>Sign up now</h3>
          <p>Enter your email address and get notified about new products. We hate spam!</p>
          <div class="input-group">
            <input type="text" class="form-control" placeholder="your email address" aria-describedby="basic-addon2">
            <a href="potepan/unfinished" class="input-group-addon" id="basic-addon2">go <i class="glyphicon glyphicon-chevron-right"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_head.html.erb
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <!-- PLUGINS CSS STYLE & GOOGLE FONT -->
  <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

  <!-- CUSTOM CSS -->

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

app/views/layouts/_header.html.erb
<!-- HEADER -->
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <!-- <li><a href="/potepan/unfinished"><i class="fa fa-twitter"></i></a></li>
            <li><a href="/potepan/unfinished"><i class="fa fa-facebook"></i></a></li> -->
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
        <% if logged_in? %>
          <ul class="list-inline pull-right">
            <li><span>
              <%= link_to 'アカウント設定', edit_potepan_user_path(current_user.id) %>
              <%= link_to "ログアウト", potepan_logout_path, method: :delete %>
            </span></li>
          </ul>
        <% else %>
          <ul class="list-inline pull-right">
            <li><span>
              <%= link_to 'ログイン', potepan_login_path %>
              <%= link_to '新規登録', new_potepan_user_path %>
            </span></li>
          </ul>
        <% end %>
        </div>
      </div>
    </div>
  </div>
  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("img/logo.png", :alt => ""), potepan_path, class: "navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown megaDropMenu <% if home_page? %> active <% end %> ">
            <%= link_to "トップページ", potepan_path %></li>
          <li class="dropdown megaDropMenu <% if shop_page? %> active <% end %> ">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">お買い物</a>
            <ul class="dropdown-menu row">
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>カテゴリから</li>
                  <% @taxons.each do |taxon| %>
                    <li><%= link_to taxon.name, potepan_category_path(taxon.id) %></li>
                  <% end %>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>ブランドから</li>
                  <% @brands.each do |brand| %>
                    <li><%= link_to brand.name, potepan_category_path(brand.id) %></li>
                  <% end %>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>カート</li>
                  <% if logged_in? %>
                  <li><%= link_to '中身を確認', potepan_order_path(@order_id) %></li>
                  <li><%= link_to '購入手続きに進む', step1_potepan_order_path(@order_id) %></li>
                  <% else %>
                  <li><%= link_to '中身を確認', potepan_login_path %></li>
                  <li><%= link_to '購入手続きに進む', potepan_login_path %></li>
                  <% end %>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>ユーザー情報</li>
                  <% if logged_in? %>
                  <li><%= link_to '登録情報の確認', potepan_user_path(current_user.id) %></li>
                  <li><%= link_to '購入履歴を見る', potepan_user_path(current_user.id) %></li>
                  <li><%= link_to 'お気に入りを見る', potepan_user_path(current_user.id) %></li>
                  <% else %>
                  <li><%= link_to '登録情報の確認', potepan_login_path %></li>
                  <li><%= link_to '購入履歴を見る', potepan_login_path %></li>
                  <li><%= link_to 'お気に入りを見る', potepan_login_path %></li>
                  <% end %>
                </ul>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/_modal.html.erb
<!-- LOGIN MODAL -->
<div class="modal fade login-modal" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">ログイン</h3>
      </div>
      <div class="modal-body">
        <%= form_tag('/potepan/unfinished', role: 'form') do %>
          <div class="form-group">
            <%= label_tag 'メールアドレス' %>
            <%= text_field_tag :email, '', { class: 'form-control', id: 'login-email'} %>
          </div>
          <div class="form-group">
            <%= label_tag 'パスワード' %>
            <%= text_field_tag :password, '', { class: 'form-control', id: 'login-password'} %>
          </div>
          <div class="checkbox">
            <%= label_tag '' %>
            <%= check_box_tag :checkbox %>
            パスワードを保存
          </div>
          <button type="submit" class="btn btn-primary btn-block">ログイン</button>
          <button type="submit" class="btn btn-link btn-block">パスワードを忘れた場合</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- SIGN UP MODAL -->
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">新規作成</h3>
      </div>
      <div class="modal-body">
        <%= form_tag('/potepan/unfinished', role: 'form') do %>
          <div class="form-group">
            <%= label_tag 'メールアドレス' %>
            <%= text_field_tag :email, '', { class: 'form-control', id: 'signyp-email'} %>
          </div>
          <div class="form-group">
            <%= label_tag 'パスワード' %>
            <%= text_field_tag :password, '', { class: 'form-control', id: 'signup-password'} %>
          </div>
          <div class="form-group">
            <%= label_tag 'パスワードの確認' %>
            <%= text_field_tag :password, '', { class: 'form-control', id: 'signup-password-confirmation'} %>
          </div>
          <button type="submit" class="btn btn-primary btn-block">新規登録</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- PORDUCT QUICK VIEW MODAL -->
<% if controller.controller_name == 'home' %>
<%= render partial: 'layouts/modal_quick_view', collection: @lated_products, as: 'product' %>
<% end %>

<% if controller.controller_name == 'categories' %>
<%= render partial: 'layouts/modal_quick_view', collection: @products, as: 'product' %>
<% end %>

<% if controller.controller_name == 'products' %>
<%= render partial: 'layouts/modal_quick_view', collection: @related_products, as: 'product' %>
<% end %>

<!-- Ajax message -->
<div class='ajax_message'>
  <div class="ajax_comment"></div>
</div>

app/views/layouts/_modal_quick_view.html.erb
<div class="modal fade quick-view quick_view_modal<%= product.id %>" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="media">
          <div class="media-left">
            <% product.images.each.with_index do |img| %>
              <%= image_tag(img.attachment.url(:product), :class => "media-object", :alt => "Image") %>
            <% end %>
          </div>
          <div class="media-body">
            <h2><%= product.name %></h2>
            <h3><%= (product.price * 110).to_i %>円</h3>
            <p><%= product.description %></p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">S</option>
                <option value="1">M</option>
                <option value="2">L</option>
              </select>
            </span>
            <div class="btn-area">
              <%= link_to potepan_orders_path(id: product.id ), method: :post, class: 'btn btn-primary btn-block' do %>
                カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render 'layouts/head' %>
  <body>
    <div class="main-wrapper">
      <%= render 'layouts/header' %>
      <div class="container pt-3 text-center">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      </div>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= render 'layouts/copy_right' %>
    </div>
    <%= render 'layouts/modal' %>
    <!-- 開発環境のみデバッグ情報を表示する -->
    <%= debug(params) if Rails.env.development? %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>